name: Metrics

on:
  schedule: [{ cron: "0 0 * * *" }]  # roda todo dia à meia-noite
  workflow_dispatch:                # permite rodar manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Use o token secreto que você adicionou
          token: ${{ secrets.METRICS_TOKEN }}

          # Configuração básica
          user: finguer
          template: classic

          # De qual repositório puxar
          repositories: controltowerweg

          # Saída do SVG
          filename: github-metrics.svg

          # Plugins que queremos
          base: header, repositories, metadata
          plugin_languages: yes
          plugin_contributors: yes
          plugin_achievements: yes
          plugin_traffic: yes
